### ISSUE TITLE
Nightline Logo is moving

### ISSUE THREAD

**Issue by Adimote** [EmilyShepherd/Personal-Website#1]
The logo for 'nightline' moves, even though it's set into the body of some text, in my opinion it shouldn't move. (see [volunteering](https://emilyshepherd.me/#volunteering) )

**Comment by EmilyShepherd** [comment]
Thanks for checking the site out. Yeah, I'd thought of this before but I thought I'd leave it to see if it grew on me; it hasn't haha. I'll take it out :+1:
